### ISSUE TITLE
model performance

### ISSUE THREAD

**Issue by handsomehu** [JeniaNovellusDx/deeplabv3_keras#1]
HI Golbstein,
Could you share some training result regarding this keras model? I download your model and train with pascal voc dataset with a 6GB GPU. I could only use two batch due to hardware limitation. However it take very  long for training. And I could not get very good result as in the tensorflow version of this model?
Could you kindly share some result from your training?
thanks,
Leon

**Comment by Golbstein** [comment]
Hi. I've uploaded the mobilenetv2 backbone weights for Pascal VOC 2012 dataset.

BTW-I'll update the code and the entire repository in the next few days with new features and better models with documentation.

**Comment by handsomehu** [comment]
Thanks man, looking forwarding for your input.
Best regards,
Leon

**Comment by Golbstein** [comment]
@handsomehu I've updated my code. Enjoy!

**Comment by handsomehu** [comment]
Great, thanks a lot man!
