### ISSUE TITLE
xception_pretrained_weights

### ISSUE THREAD

**Issue by trungpham2606** [JeniaNovellusDx/deeplabv3_keras#3]
Hello Golbstein, 

Iam implementing your training code, I wonder that can you please public the pretrained weights of your implementation with 'xception' backbone ? 

Thanks in advance.

**Comment by Golbstein** [comment]
You can download them from here:
https://github.com/bonlime/keras-deeplab-v3-plus/releases/download/1.1/deeplabv3_xception_tf_dim_ordering_tf_kernels.h5
