### ISSUE TITLE
error while using Jaccard loss

### ISSUE THREAD

**Issue by Dor256** [JeniaNovellusDx/deeplabv3_keras#6]
When i try to train with the given loss the following error accord : ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

**Comment by Golbstein** [comment]
The Jaccard index isn't a derivable function, therefore you can't use it as a loss.
Try sticking to the categorical_crossentropy or you're welcome to change the jaccard function to be derivable and share the code with us
